import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import fs from 'fs';
import path from 'path';
import { defineConfig, loadEnv, type Plugin } from 'vite';

const FIREBASE_SW_VERSION = '11.10.0';

/** Generate `public/firebase-messaging-sw.js` from Vite env (never commit secrets; use `.env`). */
function firebaseMessagingSwPlugin(): Plugin {
  return {
    name: 'firebase-messaging-sw',
    configResolved(config) {
      const env = loadEnv(config.mode, config.root, '');
      const firebaseConfig = {
        apiKey: env.VITE_FIREBASE_API_KEY || '',
        authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || '',
        projectId: env.VITE_FIREBASE_PROJECT_ID || '',
        storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET || '',
        messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
        appId: env.VITE_FIREBASE_APP_ID || '',
        measurementId: env.VITE_FIREBASE_MEASUREMENT_ID || '',
      };
      const isConfigured = Boolean(
        firebaseConfig.apiKey &&
          firebaseConfig.authDomain &&
          firebaseConfig.projectId &&
          firebaseConfig.storageBucket &&
          firebaseConfig.messagingSenderId &&
          firebaseConfig.appId
      );
      const json = JSON.stringify(firebaseConfig);
      const body = `/* Generated by Vite — do not edit. Configure Firebase via .env (VITE_FIREBASE_*). */
const firebaseConfig = ${json};
const firebaseConfigured = ${JSON.stringify(isConfigured)};
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_SW_VERSION}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_SW_VERSION}/firebase-messaging-compat.js');
if (firebaseConfigured) {
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();
  messaging.onBackgroundMessage((payload) => {
    const data = payload.data || {};
    const title = data.title || 'Neomed';
    const bodyText = data.body || '';
    return self.registration.showNotification(title, {
      body: bodyText,
      icon: '/favicon.ico',
      data: { url: '/invoices' },
    });
  });
}
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = event.notification.data && event.notification.data.url;
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url && 'focus' in client) return client.focus();
      }
      if (clients.openWindow) return clients.openWindow(url || '/invoices');
    }),
  );
});
self.addEventListener('install', (e) => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil(clients.claim()));
self.addEventListener('fetch', (e) => e.respondWith(fetch(e.request)));
`;
      const out = path.resolve(config.root, 'public/firebase-messaging-sw.js');
      fs.mkdirSync(path.dirname(out), { recursive: true });
      fs.writeFileSync(out, body, 'utf8');
    },
  };
}

export default defineConfig(() => {
  return {
    plugins: [react(), tailwindcss(), firebaseMessagingSwPlugin()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      hmr: process.env.DISABLE_HMR !== 'true',
    },
  };
});
